name: Triggered Workflow

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print message
        run: echo "Workflow in Repository B triggered!"

