name: Triggered by Source Repo Workflow

on:
  repository_dispatch:
    types: [workflow_completed]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Perform follow-up action
        run: |
          echo "Performing follow-up actions..."

